-- KeepGoing v1.2 durable job state.
-- Prototype schema only: review and apply through the normal Supabase migration workflow.
-- Stores orchestration metadata only; raw prompts, model output and credentials are deliberately excluded.

create table if not exists public.keepgoing_jobs (
  job_id text primary key
    check (job_id ~ '^kgj_[0-9a-f]{32}$'),
  owner_subject_hash text not null
    check (char_length(owner_subject_hash) between 16 and 128),
  client_request_hash text,
  engine text not null default 'agents'
    check (engine in ('agents', 'responses')),
  tool_profile text not null default 'web'
    check (tool_profile ~ '^[a-z][a-z0-9_-]{0,63}
  status text not null
    check (status in (
      'queued',
      'working',
      'continuing',
      'input_required',
      'completed',
      'failed',
      'cancelled',
      'budget_exhausted'
    )),
  version bigint not null default 1
    check (version > 0),
  attempt integer not null default 0
    check (attempt >= 0),
  max_attempts integer not null default 6
    check (max_attempts between 1 and 20),
  tokens_used bigint not null default 0
    check (tokens_used >= 0),
  token_budget_total bigint not null default 120000
    check (token_budget_total >= 1000),
  tool_calls_used integer not null default 0
    check (tool_calls_used >= 0),
  tool_call_budget_total integer not null default 30
    check (tool_call_budget_total >= 0),
  goal_hash text,
  definition_hash text,
  completion_marker text
    check (completion_marker is null or completion_marker in ('COMPLETED', 'NEEDS_USER', 'PARTIAL')),
  continuation_needed boolean not null default false,
  continuation_claim_id uuid,
  continuation_idempotency_key text
    check (continuation_idempotency_key is null or char_length(continuation_idempotency_key) between 1 and 256),
  last_assessed_turn_id text,
  start_lease_until timestamptz,
  continuation_lease_until timestamptz,
  repeated_output_count integer not null default 0
    check (repeated_output_count >= 0),
  last_output_hash text,
  safe_error_code text,
  safe_error_message text,
  started_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_progress_at timestamptz not null default now(),
  wall_deadline_at timestamptz not null,
  constraint keepgoing_jobs_request_unique
    unique (owner_subject_hash, client_request_hash)
);

-- Add tool-policy provenance when upgrading an earlier v1.2 beta schema.
alter table public.keepgoing_jobs
  add column if not exists tool_profile text not null default 'web';
alter table public.keepgoing_jobs
  add column if not exists tool_policy_hash text;
alter table public.keepgoing_jobs
  add column if not exists tool_write_capable boolean not null default false;

create index if not exists keepgoing_jobs_status_updated_idx
  on public.keepgoing_jobs (status, updated_at);

create index if not exists keepgoing_jobs_owner_updated_idx
  on public.keepgoing_jobs (owner_subject_hash, updated_at desc);

alter table public.keepgoing_jobs enable row level security;

revoke all on table public.keepgoing_jobs from public, anon, authenticated;
grant select, insert, update, delete on table public.keepgoing_jobs to service_role;

comment on table public.keepgoing_jobs is
  'Durable KeepGoing orchestration metadata. Does not store raw prompts, model output, OAuth tokens, activation tokens or passwords.';


create table if not exists public.keepgoing_job_events (
  id bigint generated by default as identity primary key,
  job_id text references public.keepgoing_jobs(job_id) on delete cascade,
  provider_event_id text unique,
  event_type text not null,
  safe_detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists keepgoing_job_events_job_created_idx
  on public.keepgoing_job_events (job_id, created_at desc);

alter table public.keepgoing_job_events enable row level security;

revoke all on table public.keepgoing_job_events from public, anon, authenticated;
grant select, insert, update, delete on table public.keepgoing_job_events to service_role;
grant usage, select on sequence public.keepgoing_job_events_id_seq to service_role;

comment on table public.keepgoing_job_events is
  'Deduplicated safe orchestration/webhook event ledger. Raw webhook bodies and secrets must not be stored.';


-- Atomically reserve a start request before any paid provider session is created.
-- A repeated owner + client_request_hash returns the original reservation.
drop function if exists public.reserve_keepgoing_job(
  text, text, text, text, text, text, integer, bigint, integer, timestamptz, timestamptz
);

create or replace function public.reserve_keepgoing_job(
  p_job_id text,
  p_owner_subject_hash text,
  p_client_request_hash text,
  p_engine text,
  p_goal_hash text,
  p_definition_hash text,
  p_max_attempts integer,
  p_token_budget_total bigint,
  p_tool_call_budget_total integer,
  p_wall_deadline_at timestamptz,
  p_start_lease_until timestamptz,
  p_tool_profile text,
  p_tool_policy_hash text,
  p_tool_write_capable boolean
)
returns setof public.keepgoing_jobs
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
begin
  insert into public.keepgoing_jobs (
    job_id,
    owner_subject_hash,
    client_request_hash,
    engine,
    tool_profile,
    tool_policy_hash,
    tool_write_capable,
    status,
    max_attempts,
    token_budget_total,
    tool_call_budget_total,
    goal_hash,
    definition_hash,
    wall_deadline_at,
    start_lease_until
  )
  values (
    p_job_id,
    p_owner_subject_hash,
    p_client_request_hash,
    p_engine,
    coalesce(nullif(p_tool_profile, ''), 'web'),
    nullif(p_tool_policy_hash, ''),
    coalesce(p_tool_write_capable, false),
    'queued',
    p_max_attempts,
    p_token_budget_total,
    p_tool_call_budget_total,
    p_goal_hash,
    p_definition_hash,
    p_wall_deadline_at,
    p_start_lease_until
  )
  on conflict (owner_subject_hash, client_request_hash) do nothing;

  if p_client_request_hash is null then
    return query
      select * from public.keepgoing_jobs where job_id = p_job_id;
  else
    return query
      select *
      from public.keepgoing_jobs
      where owner_subject_hash = p_owner_subject_hash
        and client_request_hash = p_client_request_hash;
  end if;
end;
$$;

revoke all on function public.reserve_keepgoing_job(
  text, text, text, text, text, text, integer, bigint, integer, timestamptz, timestamptz,
  text, text, boolean
) from public, anon, authenticated;

grant execute on function public.reserve_keepgoing_job(
  text, text, text, text, text, text, integer, bigint, integer, timestamptz, timestamptz,
  text, text, boolean
) to service_role;


-- Remove old terminal orchestration metadata and old safe webhook event rows.
-- Active/incomplete jobs are never deleted by this function.
create or replace function public.cleanup_keepgoing_durable_state(
  p_job_retention_days integer default 30,
  p_event_retention_days integer default 14
)
returns table (
  deleted_jobs bigint,
  deleted_events bigint
)
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_deleted_jobs bigint := 0;
  v_deleted_events bigint := 0;
begin
  if p_job_retention_days < 1 or p_job_retention_days > 3650 then
    raise exception 'p_job_retention_days must be between 1 and 3650';
  end if;
  if p_event_retention_days < 1 or p_event_retention_days > 3650 then
    raise exception 'p_event_retention_days must be between 1 and 3650';
  end if;

  delete from public.keepgoing_job_events
  where created_at < now() - make_interval(days => p_event_retention_days);
  get diagnostics v_deleted_events = row_count;

  delete from public.keepgoing_jobs
  where status in ('completed', 'failed', 'cancelled', 'budget_exhausted')
    and updated_at < now() - make_interval(days => p_job_retention_days);
  get diagnostics v_deleted_jobs = row_count;

  return query select v_deleted_jobs, v_deleted_events;
end;
$$;

revoke all on function public.cleanup_keepgoing_durable_state(integer, integer)
  from public, anon, authenticated;

grant execute on function public.cleanup_keepgoing_durable_state(integer, integer)
  to service_role;
),
  tool_policy_hash text
    check (tool_policy_hash is null or tool_policy_hash ~ '^[0-9a-f]{64}
  status text not null
    check (status in (
      'queued',
      'working',
      'continuing',
      'input_required',
      'completed',
      'failed',
      'cancelled',
      'budget_exhausted'
    )),
  version bigint not null default 1
    check (version > 0),
  attempt integer not null default 0
    check (attempt >= 0),
  max_attempts integer not null default 6
    check (max_attempts between 1 and 20),
  tokens_used bigint not null default 0
    check (tokens_used >= 0),
  token_budget_total bigint not null default 120000
    check (token_budget_total >= 1000),
  tool_calls_used integer not null default 0
    check (tool_calls_used >= 0),
  tool_call_budget_total integer not null default 30
    check (tool_call_budget_total >= 0),
  goal_hash text,
  definition_hash text,
  completion_marker text
    check (completion_marker is null or completion_marker in ('COMPLETED', 'NEEDS_USER', 'PARTIAL')),
  continuation_needed boolean not null default false,
  continuation_claim_id uuid,
  continuation_idempotency_key text
    check (continuation_idempotency_key is null or char_length(continuation_idempotency_key) between 1 and 256),
  last_assessed_turn_id text,
  start_lease_until timestamptz,
  continuation_lease_until timestamptz,
  repeated_output_count integer not null default 0
    check (repeated_output_count >= 0),
  last_output_hash text,
  safe_error_code text,
  safe_error_message text,
  started_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_progress_at timestamptz not null default now(),
  wall_deadline_at timestamptz not null,
  constraint keepgoing_jobs_request_unique
    unique (owner_subject_hash, client_request_hash)
);

create index if not exists keepgoing_jobs_status_updated_idx
  on public.keepgoing_jobs (status, updated_at);

create index if not exists keepgoing_jobs_owner_updated_idx
  on public.keepgoing_jobs (owner_subject_hash, updated_at desc);

alter table public.keepgoing_jobs enable row level security;

revoke all on table public.keepgoing_jobs from public, anon, authenticated;
grant select, insert, update, delete on table public.keepgoing_jobs to service_role;

comment on table public.keepgoing_jobs is
  'Durable KeepGoing orchestration metadata. Does not store raw prompts, model output, OAuth tokens, activation tokens or passwords.';


create table if not exists public.keepgoing_job_events (
  id bigint generated by default as identity primary key,
  job_id text references public.keepgoing_jobs(job_id) on delete cascade,
  provider_event_id text unique,
  event_type text not null,
  safe_detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists keepgoing_job_events_job_created_idx
  on public.keepgoing_job_events (job_id, created_at desc);

alter table public.keepgoing_job_events enable row level security;

revoke all on table public.keepgoing_job_events from public, anon, authenticated;
grant select, insert, update, delete on table public.keepgoing_job_events to service_role;
grant usage, select on sequence public.keepgoing_job_events_id_seq to service_role;

comment on table public.keepgoing_job_events is
  'Deduplicated safe orchestration/webhook event ledger. Raw webhook bodies and secrets must not be stored.';


-- Atomically reserve a start request before any paid provider session is created.
-- A repeated owner + client_request_hash returns the original reservation.
create or replace function public.reserve_keepgoing_job(
  p_job_id text,
  p_owner_subject_hash text,
  p_client_request_hash text,
  p_engine text,
  p_goal_hash text,
  p_definition_hash text,
  p_max_attempts integer,
  p_token_budget_total bigint,
  p_tool_call_budget_total integer,
  p_wall_deadline_at timestamptz,
  p_start_lease_until timestamptz
)
returns setof public.keepgoing_jobs
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
begin
  insert into public.keepgoing_jobs (
    job_id,
    owner_subject_hash,
    client_request_hash,
    engine,
    status,
    max_attempts,
    token_budget_total,
    tool_call_budget_total,
    goal_hash,
    definition_hash,
    wall_deadline_at,
    start_lease_until
  )
  values (
    p_job_id,
    p_owner_subject_hash,
    p_client_request_hash,
    p_engine,
    'queued',
    p_max_attempts,
    p_token_budget_total,
    p_tool_call_budget_total,
    p_goal_hash,
    p_definition_hash,
    p_wall_deadline_at,
    p_start_lease_until
  )
  on conflict (owner_subject_hash, client_request_hash) do nothing;

  if p_client_request_hash is null then
    return query
      select * from public.keepgoing_jobs where job_id = p_job_id;
  else
    return query
      select *
      from public.keepgoing_jobs
      where owner_subject_hash = p_owner_subject_hash
        and client_request_hash = p_client_request_hash;
  end if;
end;
$$;

revoke all on function public.reserve_keepgoing_job(
  text, text, text, text, text, text, integer, bigint, integer, timestamptz, timestamptz
) from public, anon, authenticated;

grant execute on function public.reserve_keepgoing_job(
  text, text, text, text, text, text, integer, bigint, integer, timestamptz, timestamptz
) to service_role;


-- Remove old terminal orchestration metadata and old safe webhook event rows.
-- Active/incomplete jobs are never deleted by this function.
create or replace function public.cleanup_keepgoing_durable_state(
  p_job_retention_days integer default 30,
  p_event_retention_days integer default 14
)
returns table (
  deleted_jobs bigint,
  deleted_events bigint
)
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_deleted_jobs bigint := 0;
  v_deleted_events bigint := 0;
begin
  if p_job_retention_days < 1 or p_job_retention_days > 3650 then
    raise exception 'p_job_retention_days must be between 1 and 3650';
  end if;
  if p_event_retention_days < 1 or p_event_retention_days > 3650 then
    raise exception 'p_event_retention_days must be between 1 and 3650';
  end if;

  delete from public.keepgoing_job_events
  where created_at < now() - make_interval(days => p_event_retention_days);
  get diagnostics v_deleted_events = row_count;

  delete from public.keepgoing_jobs
  where status in ('completed', 'failed', 'cancelled', 'budget_exhausted')
    and updated_at < now() - make_interval(days => p_job_retention_days);
  get diagnostics v_deleted_jobs = row_count;

  return query select v_deleted_jobs, v_deleted_events;
end;
$$;

revoke all on function public.cleanup_keepgoing_durable_state(integer, integer)
  from public, anon, authenticated;

grant execute on function public.cleanup_keepgoing_durable_state(integer, integer)
  to service_role;
),
  tool_write_capable boolean not null default false,
  provider_session_id text unique,
  status text not null
    check (status in (
      'queued',
      'working',
      'continuing',
      'input_required',
      'completed',
      'failed',
      'cancelled',
      'budget_exhausted'
    )),
  version bigint not null default 1
    check (version > 0),
  attempt integer not null default 0
    check (attempt >= 0),
  max_attempts integer not null default 6
    check (max_attempts between 1 and 20),
  tokens_used bigint not null default 0
    check (tokens_used >= 0),
  token_budget_total bigint not null default 120000
    check (token_budget_total >= 1000),
  tool_calls_used integer not null default 0
    check (tool_calls_used >= 0),
  tool_call_budget_total integer not null default 30
    check (tool_call_budget_total >= 0),
  goal_hash text,
  definition_hash text,
  completion_marker text
    check (completion_marker is null or completion_marker in ('COMPLETED', 'NEEDS_USER', 'PARTIAL')),
  continuation_needed boolean not null default false,
  continuation_claim_id uuid,
  continuation_idempotency_key text
    check (continuation_idempotency_key is null or char_length(continuation_idempotency_key) between 1 and 256),
  last_assessed_turn_id text,
  start_lease_until timestamptz,
  continuation_lease_until timestamptz,
  repeated_output_count integer not null default 0
    check (repeated_output_count >= 0),
  last_output_hash text,
  safe_error_code text,
  safe_error_message text,
  started_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_progress_at timestamptz not null default now(),
  wall_deadline_at timestamptz not null,
  constraint keepgoing_jobs_request_unique
    unique (owner_subject_hash, client_request_hash)
);

create index if not exists keepgoing_jobs_status_updated_idx
  on public.keepgoing_jobs (status, updated_at);

create index if not exists keepgoing_jobs_owner_updated_idx
  on public.keepgoing_jobs (owner_subject_hash, updated_at desc);

alter table public.keepgoing_jobs enable row level security;

revoke all on table public.keepgoing_jobs from public, anon, authenticated;
grant select, insert, update, delete on table public.keepgoing_jobs to service_role;

comment on table public.keepgoing_jobs is
  'Durable KeepGoing orchestration metadata. Does not store raw prompts, model output, OAuth tokens, activation tokens or passwords.';


create table if not exists public.keepgoing_job_events (
  id bigint generated by default as identity primary key,
  job_id text references public.keepgoing_jobs(job_id) on delete cascade,
  provider_event_id text unique,
  event_type text not null,
  safe_detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists keepgoing_job_events_job_created_idx
  on public.keepgoing_job_events (job_id, created_at desc);

alter table public.keepgoing_job_events enable row level security;

revoke all on table public.keepgoing_job_events from public, anon, authenticated;
grant select, insert, update, delete on table public.keepgoing_job_events to service_role;
grant usage, select on sequence public.keepgoing_job_events_id_seq to service_role;

comment on table public.keepgoing_job_events is
  'Deduplicated safe orchestration/webhook event ledger. Raw webhook bodies and secrets must not be stored.';


-- Atomically reserve a start request before any paid provider session is created.
-- A repeated owner + client_request_hash returns the original reservation.
create or replace function public.reserve_keepgoing_job(
  p_job_id text,
  p_owner_subject_hash text,
  p_client_request_hash text,
  p_engine text,
  p_goal_hash text,
  p_definition_hash text,
  p_max_attempts integer,
  p_token_budget_total bigint,
  p_tool_call_budget_total integer,
  p_wall_deadline_at timestamptz,
  p_start_lease_until timestamptz
)
returns setof public.keepgoing_jobs
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
begin
  insert into public.keepgoing_jobs (
    job_id,
    owner_subject_hash,
    client_request_hash,
    engine,
    status,
    max_attempts,
    token_budget_total,
    tool_call_budget_total,
    goal_hash,
    definition_hash,
    wall_deadline_at,
    start_lease_until
  )
  values (
    p_job_id,
    p_owner_subject_hash,
    p_client_request_hash,
    p_engine,
    'queued',
    p_max_attempts,
    p_token_budget_total,
    p_tool_call_budget_total,
    p_goal_hash,
    p_definition_hash,
    p_wall_deadline_at,
    p_start_lease_until
  )
  on conflict (owner_subject_hash, client_request_hash) do nothing;

  if p_client_request_hash is null then
    return query
      select * from public.keepgoing_jobs where job_id = p_job_id;
  else
    return query
      select *
      from public.keepgoing_jobs
      where owner_subject_hash = p_owner_subject_hash
        and client_request_hash = p_client_request_hash;
  end if;
end;
$$;

revoke all on function public.reserve_keepgoing_job(
  text, text, text, text, text, text, integer, bigint, integer, timestamptz, timestamptz
) from public, anon, authenticated;

grant execute on function public.reserve_keepgoing_job(
  text, text, text, text, text, text, integer, bigint, integer, timestamptz, timestamptz
) to service_role;


-- Remove old terminal orchestration metadata and old safe webhook event rows.
-- Active/incomplete jobs are never deleted by this function.
create or replace function public.cleanup_keepgoing_durable_state(
  p_job_retention_days integer default 30,
  p_event_retention_days integer default 14
)
returns table (
  deleted_jobs bigint,
  deleted_events bigint
)
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_deleted_jobs bigint := 0;
  v_deleted_events bigint := 0;
begin
  if p_job_retention_days < 1 or p_job_retention_days > 3650 then
    raise exception 'p_job_retention_days must be between 1 and 3650';
  end if;
  if p_event_retention_days < 1 or p_event_retention_days > 3650 then
    raise exception 'p_event_retention_days must be between 1 and 3650';
  end if;

  delete from public.keepgoing_job_events
  where created_at < now() - make_interval(days => p_event_retention_days);
  get diagnostics v_deleted_events = row_count;

  delete from public.keepgoing_jobs
  where status in ('completed', 'failed', 'cancelled', 'budget_exhausted')
    and updated_at < now() - make_interval(days => p_job_retention_days);
  get diagnostics v_deleted_jobs = row_count;

  return query select v_deleted_jobs, v_deleted_events;
end;
$$;

revoke all on function public.cleanup_keepgoing_durable_state(integer, integer)
  from public, anon, authenticated;

grant execute on function public.cleanup_keepgoing_durable_state(integer, integer)
  to service_role;
